# config.yml

#语言配置
language: "zh_CN"

# 金币低于此值时掉落物品
dropThreshold: 10000.0

#是否按照物品计算
calculateBasedOnItems: true

#浮动大小
itemValueVariance: 0.5

# 经验扣除百分比
expDeductionPercentages:
  default: 2
  vip: 3
  admin: 5

# 金币扣除百分比
moneyDeductionPercentages:
  default: 5
  vip: 7
  admin: 10

# 物品扣除百分比
itemValuePercentages:
  default: 1.0
  vip: 0.5

#检查更新
checkForUpdates: true

#统计信息
enableMetrics: true